"use client";

import type { Metadata } from "next";
import "./globals.css";
import { Inter, Noto_Sans_KR } from "next/font/google";
import { usePathname } from "next/navigation";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  return (
    <html>
      <body className="w-full bg-[#ebebeb] text-[#282828] font-inter font-[400] leading-normal scrollbar-hide">
        {pathname !== "/auth" && (
          <>
            <header>dddd</header>
          </>
        )}
        {children}
      </body>
    </html>
  );
}
